### ISSUE TITLE
Modified gen_candidate.py

### ISSUE THREAD

**Issue by jeewoo1025** [yixinL7/BRIO#4]
Hi, I ask one question about `gen_candidate.py` code. When I perform that code on **1 NVIDIA RTX 3090 GPU**, the runtime error (CUDA out of memory) happened. Therefore, I modified the code as below, is this okay?

▶ Before (`gen_candidate.py` 83 ~ 85 lines)
```python
with torch.no_grad():
     batch = tok.prepare_seq2seq_batch(src_texts=slines, return_tensors="pt").to(device)
     gen = model.generate(**batch, num_return_sequences=128, num_beam_groups=16, diversity_penalty=0.1, num_beams=128, length_penalty=0.6)
     dec: List[str] = tok.batch_decode(gen, skip_special_tokens=True)
```

▶ After (`gen_candidate.py` 83 ~ 85 lines)
```python
max_length = 64
with torch.no_grad():
     batch = tok.prepare_seq2seq_batch(src_texts=slines, return_tensors="pt", max_length=max_length, pad_to_max_length=True, truncation=True).to(device)
     gen = model.generate(**batch, num_return_sequences=128, num_beam_groups=16, diversity_penalty=0.1, num_beams=128, length_penalty=0.6)
     dec: List[str] = tok.batch_decode(gen, skip_special_tokens=True)
```

**Comment by yixinL7** [comment]
Hi! I think setting the max length of the _source article_ to be 64 is probably not a good idea because the average length of the source article is around 500 tokens. Alternatively, you may consider using a smaller batch size (1) in line [74](https://github.com/yixinL7/BRIO/blob/main/gen_candidate.py#L74).
If that still doesn't work, you may consider the following change:
```python
beam_size = 4
with torch.no_grad():
    batch = tok.prepare_seq2seq_batch(src_texts=slines, return_tensors="pt").to(device)
    gen = model.generate(**batch, num_return_sequences=16 * beam_size, num_beam_groups=16, diversity_penalty=0.1, num_beams=16 * beam_size, length_penalty=0.6)
    dec: List[str] = tok.batch_decode(gen, skip_special_tokens=True)
dec = [dec[i] for i in range(len(dec)) if i % beam_size == 0]
```
Setting the beam size to a smaller value may affect the output quality, but I believe the difference should be small.

**Comment by jeewoo1025** [comment]
It works well after I changed the batch size from 2 to 1 in line 74. Thank you :)
